//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalysisData.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an admin!.
        /// </summary>
        internal static string AdminExistenceException {
            get {
                return ResourceManager.GetString("AdminExistenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category already exist!.
        /// </summary>
        internal static string CategoryAlreadyExist {
            get {
                return ResourceManager.GetString("CategoryAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not exists in our system!.
        /// </summary>
        internal static string CategoryResultNotFoundException {
            get {
                return ResourceManager.GetString("CategoryResultNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have this role in db ! .
        /// </summary>
        internal static string DuplicateRoleException {
            get {
                return ResourceManager.GetString("DuplicateRoleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have user with this information !.
        /// </summary>
        internal static string DuplicateUserException {
            get {
                return ResourceManager.GetString("DuplicateUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge not found exception !.
        /// </summary>
        internal static string EdgeNotFoundException {
            get {
                return ResourceManager.GetString("EdgeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have this file ! .
        /// </summary>
        internal static string FileExistenceException {
            get {
                return ResourceManager.GetString("FileExistenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email format !.
        /// </summary>
        internal static string InvalidEmailFormatException {
            get {
                return ResourceManager.GetString("InvalidEmailFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid !.
        /// </summary>
        internal static string InvalidPasswordException {
            get {
                return ResourceManager.GetString("InvalidPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password format is invlaid ! .
        /// </summary>
        internal static string InvalidPasswordFormatException {
            get {
                return ResourceManager.GetString("InvalidPasswordFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone number format !.
        /// </summary>
        internal static string InvalidPhoneNumberFormatException {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node not found Exception ! .
        /// </summary>
        internal static string NodeNotFoundException {
            get {
                return ResourceManager.GetString("NodeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file uploaded exception !.
        /// </summary>
        internal static string NoFileUploadedException {
            get {
                return ResourceManager.GetString("NoFileUploadedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not match ! .
        /// </summary>
        internal static string PasswordMismatchException {
            get {
                return ResourceManager.GetString("PasswordMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not have this role !.
        /// </summary>
        internal static string RoleNotFoundException {
            get {
                return ResourceManager.GetString("RoleNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token expired  !.
        /// </summary>
        internal static string TokenExpiredException {
            get {
                return ResourceManager.GetString("TokenExpiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token not found in cookies !.
        /// </summary>
        internal static string TokenNotFoundInCookieException {
            get {
                return ResourceManager.GetString("TokenNotFoundInCookieException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user not found ! .
        /// </summary>
        internal static string UserNotFoundException {
            get {
                return ResourceManager.GetString("UserNotFoundException", resourceCulture);
            }
        }
    }
}
